import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import '@/styles/globals.css'
import Container from '@/components/container'

const poppins = Poppins({ 
  subsets: ['latin'], 
  weight: ["300", "400", "700", "900"] 
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${poppins.className} bg-background`}>
        <Container>
          {children}
        </Container>
      </body>
    </html>
  )
}
